### ISSUE TITLE
Rebuild Nexu Index - Error saving nexu relation

### ISSUE THREAD

**Issue by ninjaonsafari** [dawoe/umbraco-nexu#16]
When i rebuild the index i get a bunch of errors in the `umbracoLog`. Do I have to worry about these errors. Because the package works as excepted.

**UmbracoLog:**
```
2017-07-28 17:50:14,680 [P23068/D13/TNexuRebuildJob] ERROR Umbraco.Core.Persistence.UmbracoDatabase - Exception (9d73ff54).
System.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_umbracoRelation_umbracoNode1". The conflict occurred in database "umb_XXXX", table "umb_XXXX.umbracoNode", column 'id'.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteScalar()
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.<>c__DisplayClassa.<ExecuteScalarWithRetry>b__9()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteScalarWithRetry(IDbCommand command, RetryPolicy cmdRetryPolicy, RetryPolicy conRetryPolicy)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteScalarWithRetry(IDbCommand command, RetryPolicy retryPolicy)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteScalarWithRetry(IDbCommand command)
   at Umbraco.Core.Persistence.Database.Insert(String tableName, String primaryKeyName, Boolean autoIncrement, Object poco)
ClientConnectionId:325e7b7c-cad8-4e3b-b606-da931354cae4
Error Number:547,State:0,Class:16
```

**Comment by dawoe** [comment]
Hi,

I think this caused when a id is found somewhere in your content when a item no longer exists. Than creating the relation will fail on the foreign key constraint.

Don't know how elegantly handle this.

Dave

**Comment by jaandrews** [comment]
I'm getting this error as well. Does it attempt to store the relation if the id is 0? I've noticed that the obsolete multinode treepicker goes to 0 when it's empty instead of an empty string, which may explain why I encounter this error.

**Comment by dawoe** [comment]
Could be the case. I just catch all unexpected errors when indexing and log them.
