### ISSUE TITLE
LeBlender grid editor parsing error

### ISSUE THREAD

**Issue by darkoopala** [dawoe/umbraco-nexu#31]
When I run rebuild I get this error in the log file:
`2018-05-08 05:32:21,279 [P12300/D7/T137] ERROR Our.Umbraco.Nexu.Parsers.GridEditorParsers.Community.LeBlenderGridEditorParser - Error parsing le blender grid editor
System.NullReferenceException: Object reference not set to an instance of an object.
at Our.Umbraco.Nexu.Parsers.PropertyParsers.Core.ContentPickerParser.IsParserFor(IDataTypeDefinition dataTypeDefinition) in C:\projects\umbraco-nexu\Source\Our.Umbraco.Nexu.Parsers\PropertyParsers\Core\ContentPickerParser.cs:line 64
at Our.Umbraco.Nexu.Parsers.GridEditorParsers.Community.LeBlenderGridEditorParser.<>c_DisplayClass4_0.<GetLinkedEntities>b_0(IPropertyParser x) in C:\projects\umbraco-nexu\Source\Our.Umbraco.Nexu.Parsers\GridEditorParsers\Community\LeBlenderGriddEditorParser.cs:line 110
at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
at Our.Umbraco.Nexu.Parsers.GridEditorParsers.Community.LeBlenderGridEditorParser.GetLinkedEntities(String value) in C:\projects\umbraco-nexu\Source\Our.Umbraco.Nexu.Parsers\GridEditorParsers\Community\LeBlenderGriddEditorParser.cs:line 108`

Kind regards,
Darko

**Comment by dawoe** [comment]
Hi Darko,

The error suggest it happens in a grid editor that uses the content picker on this line https://github.com/dawoe/umbraco-nexu/blob/develop/Source/Our.Umbraco.Nexu.Parsers/PropertyParsers/Core/ContentPickerParser.cs#L64

Can you provide some more info like Umbraco version, Nexu version and maybe your leblender configuration so we can try to reproduce

Dave

**Comment by darkoopala** [comment]
Hi Dave,

Thanks for the fast reply :)

Here are the details:
- Umbraco version: 7.9.2

- Nexu version:  1.5.0

- LeBlender version: 1.0.9.2

Target framework for all packages is net45.
By LeBlender configuration you mean on the grid.editors.config.js?

Kind regards,
Darko

**Comment by dawoe** [comment]
Hi @darkoopala 

I wasn't able to reproduce this on my sites using Leblender. I added some extra logging to the parser for leblender so it also logs the grid value. 

That would give some more input when the issue occurs again. 

You can test this in the latest beta version.

I'm closing this issue. If it happens again feel free to open a new issue
