### ISSUE TITLE
V8 version install issue

### ISSUE THREAD

**Issue by ismailmayat** [dawoe/umbraco-nexu#57]
When installing package or nuget in v8 with sql server as the database I get the following error:

> Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.Data.SqlClient.SqlException: Cannot create more than one clustered index on table 'Nexu_Relations'. Drop the existing clustered index 'IX_Nexu_Relations_parent_udi' before creating another.
  at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
  at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
  at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
  at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
  at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
  at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
  at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 284
  at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in d:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172
  at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
  at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)
  at Umbraco.Core.Migrations.MigrationExpressionBase.ExecuteStatement(StringBuilder stmtBuilder) in d:\a\1\s\src\Umbraco.Core\Migrations\MigrationExpressionBase.cs:line 121
  at Umbraco.Core.Migrations.MigrationExpressionBase.Execute() in d:\a\1\s\src\Umbraco.Core\Migrations\MigrationExpressionBase.cs:line 77
  at Umbraco.Core.Migrations.MigrationExpressionBase.Execute() in d:\a\1\s\src\Umbraco.Core\Migrations\MigrationExpressionBase.cs:line 86
  at Umbraco.Core.Migrations.MigrationBase.Umbraco.Core.Migrations.IMigration.Migrate() in d:\a\1\s\src\Umbraco.Core\Migrations\MigrationBase.cs:line 73
  at Umbraco.Core.Migrations.MigrationPlan.Execute(IScope scope, String fromState, IMigrationBuilder migrationBuilder, ILogger logger) in d:\a\1\s\src\Umbraco.Core\Migrations\MigrationPlan.cs:line 312
  at Umbraco.Core.Migrations.Upgrade.Upgrader.Execute(IScopeProvider scopeProvider, IMigrationBuilder migrationBuilder, IKeyValueService keyValueService, ILogger logger) in d:\a\1\s\src\Umbraco.Core\Migrations\Upgrade\Upgrader.cs:line 67
  at Our.Umbraco.Nexu.Core.Composing.Components.MigrationComponent.Initialize()
  at Umbraco.Core.Composing.ComponentCollection.Initialize() in d:\a\1\s\src\Umbraco.Core\Composing\ComponentCollection.cs:line 31
  at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in d:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 159

**Comment by dawoe** [comment]
This one is fixed in the lastest beta release

**Comment by OwainJ** [comment]
@dawoe Hi Dave, sorry to bump this thread, but do you have an eta on when a stable release for V8 will be out?

**Comment by dawoe** [comment]
Hi @OwainJ 

I'm finalizing the release. Will be probably released in 2 weeks time. But you could use the beta version. It is pretty stable. I know @ismailmayat is using it on a site.

Dave

**Comment by OwainJ** [comment]
Hi @dawoe 

Awesome, thanks for your reply!
I've been testing the beta version and it seems to work brilliantly!

Owain

**Comment by dawoe** [comment]
Hi @OwainJ 

Thanks for testing. Last week I made some changes so it also works for list views. And it the list where it shows the relations it now supports infinite editing.

Other things I still want to do is 
- Move all text to language files
- Handle delete/unpublish when a item deeper in the tree is in use. 
- Show outgoing relations as well

If you find any issues make sure to log them.

Dave

**Comment by OwainJ** [comment]
@dawoe Awesome, will do! :)
