### ISSUE TITLE
v8 rebuild issue

### ISSUE THREAD

**Issue by ismailmayat** [dawoe/umbraco-nexu#58]
When I rebuild I get the following errors in my log:

> System.InvalidCastException: Unable to cast object of type 'Umbraco.Core.Persistence.FaultHandling.RetryDbConnection' to type 'System.Data.SqlClient.SqlConnection'.
   at NPoco.SqlBulkCopyHelper.<>c.<.cctor>b__7_0(DbConnection dbConn)
   at NPoco.SqlBulkCopyHelper.BulkInsert[T](IDatabase db, IEnumerable`1 list, SqlBulkCopyOptions sqlBulkCopyOptions)
   at NPoco.Database.InsertBulk[T](IEnumerable`1 pocos)
   at Our.Umbraco.Nexu.Core.Repositories.NexuRelationRepository.PersistRelationsForContentItem(Udi contentItemUdi, IEnumerable`1 relations) in C:\projects\umbraco-nexu\src\Our.Umbraco.Nexu.Core\Repositories\NexuRelationRepository.cs:line 52
   at Our.Umbraco.Nexu.Core.Services.NexuEntityParsingService.SaveRelationsForContentItem(IContent content, IEnumerable`1 relations) in C:\projects\umbraco-nexu\src\Our.Umbraco.Nexu.Core\Services\NexuEntityParsingService.cs:line 216
   at Our.Umbraco.Nexu.Core.Services.NexuEntityParsingService.ParseContent(IContent content) in C:\projects\umbraco-nexu\src\Our.Umbraco.Nexu.Core\Services\NexuEntityParsingService.cs:line 78

when saving an item I get similar error:

> System.InvalidCastException: Unable to cast object of type 'Umbraco.Core.Persistence.FaultHandling.RetryDbConnection' to type 'System.Data.SqlClient.SqlConnection'.
   at NPoco.SqlBulkCopyHelper.<>c.<.cctor>b__7_0(DbConnection dbConn)
   at NPoco.SqlBulkCopyHelper.BulkInsert[T](IDatabase db, IEnumerable`1 list, SqlBulkCopyOptions sqlBulkCopyOptions)
   at NPoco.Database.InsertBulk[T](IEnumerable`1 pocos)

**Comment by dawoe** [comment]
Hi @ismailmayat is this on SQL server or sql ce ?

**Comment by ismailmayat** [comment]
this is on sql server

**Comment by dawoe** [comment]
Hi @ismailmayat 

This is fixed in the latest beta.

Some clever guy at the forum pointed me to the right direction : https://our.umbraco.com/forum/using-umbraco-and-getting-started/99362-npoco-in-v8-save-issue

**Comment by ismailmayat** [comment]
hah, awesomes
