### ISSUE TITLE
Hi Dave, we have an error with nexu package version 2.3.0 with items in a collection with relations to other items if we select an item in the list and press delete

### ISSUE THREAD

**Issue by stefanbesteman-weareyou** [dawoe/umbraco-nexu#84]
It is a solution with 2 languages 'nl' and 'en' in umbraco 8.11.1

at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at Umbraco.Core.Models.Content.IsCulturePublished(String culture) in D:\a\1\s\src\Umbraco.Core\Models\Content.cs:line 210
   at Our.Umbraco.Nexu.Core.Services.NexuEntityRelationService.GetUsedItemsFromList(IList`1 udis) in C:\projects\umbraco-nexu\src\Our.Umbraco.Nexu.Core\Services\NexuEntityRelationService.cs:line 174
   at Our.Umbraco.Nexu.Web.Api.RelationCheckApiController.CheckLinkedItems(String[] udis) in C:\projects\umbraco-nexu\src\Our.Umbraco.Nexu.Web\Api\RelationCheckApiController.cs:line 76
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()

**Comment by stefanbesteman-weareyou** [comment]
Hi Dave, Any updates on my problem?

**Comment by dawoe** [comment]
Hi @stefanbesteman-weareyou 

Totally missed this one. Where are you trying to delete the item. Through the dialog on the item. Or is it in a list view ?

Dave

**Comment by stefanbesteman-weareyou** [comment]
In a list view


Stefan Besteman
Software Engineer
iO - Campus Den Bosch
Sint Jorisstraat 129 - 5211 HA 's-Hertogenbosch
T: +31418572275 - M: +31638749925
www.iodigital.com
Van: Dave Woestenborghs ***@***.***>
Verzonden: dinsdag 19 april 2022 16:13
Aan: dawoe/umbraco-nexu ***@***.***>
CC: Stefan Besteman ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [dawoe/umbraco-nexu] Hi Dave, we have an error with nexu package version 2.3.0 with items in a collection with relations to other items if we select an item in the list and press delete (Issue #84)


Hi @stefanbesteman-weareyou<https://github.com/stefanbesteman-weareyou>

Totally missed this one. Where are you trying to delete the item. Through the dialog on the item. Or is it in a list view ?

Dave

**Comment by stefanbesteman-weareyou** [comment]
Hi Dave,

Did you have time to look into the issue?

Greetings
Stefan


Stefan Besteman
Software Engineer
iO - Campus Den Bosch
Sint Jorisstraat 129 - 5211 HA 's-Hertogenbosch
T: +31418572275 - M: +31638749925
www.iodigital.com
Van: Stefan Besteman ***@***.***>
Verzonden: dinsdag 19 april 2022 16:14
Aan: dawoe/umbraco-nexu ***@***.***>; dawoe/umbraco-nexu ***@***.***>
CC: Stefan Besteman ***@***.***>; Mention ***@***.***>
Onderwerp: RE: [dawoe/umbraco-nexu] Hi Dave, we have an error with nexu package version 2.3.0 with items in a collection with relations to other items if we select an item in the list and press delete (Issue #84)

In a list view


Stefan​ Besteman
Software Engineer
***@***.***
iO ‑ Campus Den Bosch
Sint Jorisstraat 129 ‑ 5211 HA 's‑Hertogenbosch
T: +31418572275<tel:+31418572275>
 ‑
M: +31638749925<tel:+31638749925>
www.iodigital.com<http://www.iodigital.com/>
Van: Dave Woestenborghs ***@***.******@***.***>>
Verzonden: dinsdag 19 april 2022 16:13
Aan: dawoe/umbraco-nexu ***@***.******@***.***>>
CC: Stefan Besteman ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Onderwerp: Re: [dawoe/umbraco-nexu] Hi Dave, we have an error with nexu package version 2.3.0 with items in a collection with relations to other items if we select an item in the list and press delete (Issue #84)


Hi @stefanbesteman-weareyou<https://github.com/stefanbesteman-weareyou>

Totally missed this one. Where are you trying to delete the item. Through the dialog on the item. Or is it in a list view ?

Dave

**Comment by stefanbesteman-weareyou** [comment]
Ha Dave,

Sorry dat ik je via deze weg benader.

Maar heb een vraag waarvan ik hoop dat jij het misschien nog weet.

Voor project ibn, zijn er ooit azure functions live gezet. Daar moet nu een aanpassing voor gemaakt worden, alleen niemand weet waar de sourcecode van deze azure functions staat.

Heb jij misschien een idee?

Groet,
Stefan Besteman


Stefan Besteman
Software Engineer
iO - Campus Den Bosch
Sint Jorisstraat 129 - 5211 HA 's-Hertogenbosch
T: +31418572275 - M: +31638749925
www.iodigital.com
From: Stefan Besteman ***@***.***>
Sent: Tuesday, April 19, 2022 4:14 PM
To: dawoe/umbraco-nexu ***@***.***>; dawoe/umbraco-nexu ***@***.***>
Cc: Stefan Besteman ***@***.***>; Mention ***@***.***>
Subject: RE: [dawoe/umbraco-nexu] Hi Dave, we have an error with nexu package version 2.3.0 with items in a collection with relations to other items if we select an item in the list and press delete (Issue #84)

In a list view


Stefan​ Besteman
Software Engineer
***@***.***
iO ‑ Campus Den Bosch
Sint Jorisstraat 129 ‑ 5211 HA 's‑Hertogenbosch
T: +31418572275<tel:+31418572275>
 ‑
M: +31638749925<tel:+31638749925>
www.iodigital.com<http://www.iodigital.com/>
Van: Dave Woestenborghs ***@***.******@***.***>>
Verzonden: dinsdag 19 april 2022 16:13
Aan: dawoe/umbraco-nexu ***@***.******@***.***>>
CC: Stefan Besteman ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Onderwerp: Re: [dawoe/umbraco-nexu] Hi Dave, we have an error with nexu package version 2.3.0 with items in a collection with relations to other items if we select an item in the list and press delete (Issue #84)


Hi @stefanbesteman-weareyou<https://github.com/stefanbesteman-weareyou>

Totally missed this one. Where are you trying to delete the item. Through the dialog on the item. Or is it in a list view ?

Dave

**Comment by stefanbesteman-weareyou** [comment]
Ha Dave,

Sorry dat ik je via deze weg benader.

Maar heb een vraag waarvan ik hoop dat jij het misschien nog weet.

Voor project ibn, zijn er ooit azure functions live gezet. Daar moet nu een aanpassing voor gemaakt worden, alleen niemand weet waar de sourcecode van deze azure functions staat.

Heb jij misschien een idee?

Groet,
Stefan Besteman


Stefan Besteman
Software Engineer
iO - Campus Den Bosch
Sint Jorisstraat 129 - 5211 HA 's-Hertogenbosch
T: +31418572275 - M: +31638749925
www.iodigital.com
From: Stefan Besteman ***@***.******@***.***>>
Sent: Tuesday, April 19, 2022 4:14 PM
To: dawoe/umbraco-nexu ***@***.******@***.***>>; dawoe/umbraco-nexu ***@***.******@***.***>>
Cc: Stefan Besteman ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Subject: RE: [dawoe/umbraco-nexu] Hi Dave, we have an error with nexu package version 2.3.0 with items in a collection with relations to other items if we select an item in the list and press delete (Issue #84)

In a list view


Stefan​ Besteman
Software Engineer
***@***.***
iO ‑ Campus Den Bosch
Sint Jorisstraat 129 ‑ 5211 HA 's‑Hertogenbosch
T: +31418572275<tel:+31418572275>
 ‑
M: +31638749925<tel:+31638749925>
www.iodigital.com<http://www.iodigital.com/>
Van: Dave Woestenborghs ***@***.******@***.***>>
Verzonden: dinsdag 19 april 2022 16:13
Aan: dawoe/umbraco-nexu ***@***.******@***.***>>
CC: Stefan Besteman ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Onderwerp: Re: [dawoe/umbraco-nexu] Hi Dave, we have an error with nexu package version 2.3.0 with items in a collection with relations to other items if we select an item in the list and press delete (Issue #84)


Hi @stefanbesteman-weareyou<https://github.com/stefanbesteman-weareyou>

Totally missed this one. Where are you trying to delete the item. Through the dialog on the item. Or is it in a list view ?

Dave
